version: '3'

services:
  todoserver:
    restart: always
    build: .
    depends_on:
      - tododb
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - DB_URL=jdbc:mysql://tododb:3306/fhlugdb
      - DB_USER=fhlug
      - DB_PASSWORD=123
  tododb:
    restart: always
    image: mariadb
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=fhlug
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=fhlugdb
    volumes:
      - ./dbdata:/var/lib/mysql
