version: '3'

services:
  todo-list:
    build:
      context: "../../03-dockerfile/todo-list-jvm"
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - server.port=8080
      - spring.datasource.url=jdbc:mariadb://db:3306/tododb
      - spring.datasource.username=dbuser
      - spring.datasource.password=dbpw
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  db:
    image: mariadb:10.10.2
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tododb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
